### ISSUE TITLE
Error uploading shapefile to spatial-beta

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/spatial-hub#67]
When attempting to upload a shapefile to spatial-beta using both Firefox and Safari on macOS, the interface is stuck looking like the screenshot below (web console shows an HTTP 500 response to the /portal/postAreaFile/shp request) and errors similar to the following appear in the log file on the server.

The Content-Type according to Firefox and Safari web consoles are both ``multipart/form-data; boundary=.....``

<img width="1279" alt="screen shot 2018-03-29 at 9 30 28 am" src="https://user-images.githubusercontent.com/82365/38059848-ddfee20e-3333-11e8-9249-cf72fe600efb.png">

```
09:24:54.821 [http-bio-8080-exec-745] ERROR o.g.w.errors.GrailsExceptionResolver - GroovyCastException occurred when processing request: [POST] /portal/postAreaFile/shp
Cannot cast object 'org.springframework.web.multipart.support.StandardMultipartHttpServletRequest$StandardMultipartFile@21bcfa1e' with class 'org.springframework.web.multipart.support.StandardMultipartHttpServletRequest$StandardMultipartFile' to class 'org.springframework.web.multipart.commons.CommonsMultipartFile'. Stacktrace follows:
org.codehaus.groovy.runtime.typehandling.GroovyCastException: Cannot cast object 'org.springframework.web.multipart.support.StandardMultipartHttpServletRequest$StandardMultipartFile@21bcfa1e' with class 'org.springframework.web.multipart.support.StandardMultipartHttpServletRequest$StandardMultipartFile' to class 'org.springframework.web.multipart.commons.CommonsMultipartFile'
	at au.org.ala.spatial.portal.PortalController.postAreaFile(PortalController.groovy:286)
	at org.grails.core.DefaultGrailsControllerClass$MethodHandleInvoker.invoke(DefaultGrailsControllerClass.java:223)
	at org.grails.core.DefaultGrailsControllerClass.invoke(DefaultGrailsControllerClass.java:188)
	at org.grails.web.mapping.mvc.UrlMappingsInfoHandlerAdapter.handle(UrlMappingsInfoHandlerAdapter.groovy:90)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:55)
	at org.grails.web.servlet.mvc.GrailsWebRequestFilter.doFilterInternal(GrailsWebRequestFilter.java:77)
	at au.org.ala.cas.client.AlaHttpServletRequestWrapperFilter.doFilter(AlaHttpServletRequestWrapperFilter.java:81)
	at au.org.ala.cas.client.UriFilter.doFilter(UriFilter.java:188)
	at org.jasig.cas.client.validation.AbstractTicketValidationFilter.doFilter(AbstractTicketValidationFilter.java:236)
	at au.org.ala.cas.client.UriFilter.doFilter(UriFilter.java:188)
	at org.jasig.cas.client.authentication.AuthenticationFilter.doFilter(AuthenticationFilter.java:155)
	at au.org.ala.cas.client.UriFilter.doFilter(UriFilter.java:188)
	at org.jasig.cas.client.session.SingleSignOutFilter.doFilter(SingleSignOutFilter.java:97)
	at org.grails.web.filters.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:67)
	at org.springframework.boot.web.support.ErrorPageFilter.doFilter(ErrorPageFilter.java:115)
	at org.springframework.boot.web.support.ErrorPageFilter.access$000(ErrorPageFilter.java:59)
	at org.springframework.boot.web.support.ErrorPageFilter$1.doFilterInternal(ErrorPageFilter.java:90)
	at org.springframework.boot.web.support.ErrorPageFilter.doFilter(ErrorPageFilter.java:108)
	at com.github.ziplet.filter.compression.CompressingFilter.doFilter(CompressingFilter.java:300)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by adam-collins** [comment]
example shape file
http://spatial.ala.org.au/layers-service/shape/shp/3742602
