### ISSUE TITLE
Nearest locality tool

### ISSUE THREAD

**Issue by adam-collins** [AtlasOfLivingAustralia/spatial-hub#77]
Cancel http get when closed to prevent points appearing on the map later.

**Comment by adam-collins** [comment]
exception to fix
```
2018-04-17 11:30:58.270 ERROR --- [o-8080-exec-884] o.g.web.errors.GrailsExceptionResolver   : NullPointerException occurred when processing request: [GET] /ws/objects/cl915/-24.126701958681668/131.396484375
Stacktrace follows:

java.lang.NullPointerException: null
        at au.org.ala.layers.dao.ObjectDAOImpl.updateObjectWms(ObjectDAOImpl.java:640)
        at au.org.ala.layers.dao.ObjectDAOImpl.getNearestObjectByIdAndLocation(ObjectDAOImpl.java:606)
        at au.org.ala.layers.ObjectController.fieldObjectsPoint(ObjectController.groovy:152)

```
