### ISSUE TITLE
Area report not working for polygon area

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/spatial-hub#92]
Steps to reproduce:
- Add to map -> area -> Gazetteer polygon -> next -> search for "narrabundah", select first result -> next
- polygon appears on map (doesn't seem to auto-zoom though)
- view area report for 'Narrabundah' link (quick links)

Nothing happens
Error in JS console:

```
application.unminified.js:2082 Error: [$parse:lexerr] http://errors.angularjs.org/1.5.8/$parse/lexerr?p0=Unexpected%20nextharacter%20&p1=s%2088-88%20%5B%5E%5D&p2=selectedArea%20!%3D%3D%20undefined%20%26%26%20selectedArea.wkt%20!%3D%3D%20undefined%20%26%26%20selectedArea.wkt.match(%2F%5EPOINT%2F)
    at https://spatial-beta.ala.org.au/assets/application-d556a9e62ef57aa11d98104a82cbe2cc.js:1227:399
    at zd.throwError (https://spatial-beta.ala.org.au/assets/application-d556a9e62ef57aa11d98104a82cbe2cc.js:1438:417)
    at zd.lex (https://spatial-beta.ala.org.au/assets/application-d556a9e62ef57aa11d98104a82cbe2cc.js:1436:102)
    at S.ast (https://spatial-beta.ala.org.au/assets/application-d556a9e62ef57aa11d98104a82cbe2cc.js:1442:389)
    at $b.compile (https://spatial-beta.ala.org.au/assets/application-d556a9e62ef57aa11d98104a82cbe2cc.js:1452:354)
    at Ad.parse (https://spatial-beta.ala.org.au/assets/application-d556a9e62ef57aa11d98104a82cbe2cc.js:1481:117)
    at l (https://spatial-beta.ala.org.au/assets/application-d556a9e62ef57aa11d98104a82cbe2cc.js:1346:342)
    at c.$watch (https://spatial-beta.ala.org.au/assets/application-d556a9e62ef57aa11d98104a82cbe2cc.js:1360:210)
    at Object.<anonymous> (https://spatial-beta.ala.org.au/assets/application-d556a9e62ef57aa11d98104a82cbe2cc.js:2091:283)
    at https://spatial-beta.ala.org.au/assets/application-d556a9e62ef57aa11d98104a82cbe2cc.js:1237:66
```

**Comment by qifeng-bai** [comment]
May related issue:  
getSpeciesLayerQuery method is called. Question? shall it be called?
